[theme]
primaryColor = "#FFFFFF"        # botones, links, elementos activos
backgroundColor = "#000000"                # fondo de la página
secondaryBackgroundColor = "#000000"       # fondo del sidebar y inputs
textColor = "#FFFFFF"                      # color del texto principal
font = "sans serif"